# Generated by Django 5.1.1 on 2024-09-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment'),
        ('core', '0002_doctor_bio_doctor_contact_doctor_email_and_more'),
    ]

    operations = [
    ]
